// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1QdS4T69GbIfuvgnJ9gEYpTjAB4vKg6g',
    appId: '1:727123421542:web:336025e61b3c68793f80a7',
    messagingSenderId: '727123421542',
    projectId: 'evide-school-parent',
    authDomain: 'evide-school-parent.firebaseapp.com',
    storageBucket: 'evide-school-parent.firebasestorage.app',
    measurementId: 'G-0097H33B5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU5B-9CaArRQMv26k6JwIfvDHNCCoBknU',
    appId: '1:727123421542:android:f9dabd2950de23763f80a7',
    messagingSenderId: '727123421542',
    projectId: 'evide-school-parent',
    storageBucket: 'evide-school-parent.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0JFT7GrACfEUfSBmiWGfnJy9eF7grni4',
    appId: '1:727123421542:ios:2d202da10d7d1cc33f80a7',
    messagingSenderId: '727123421542',
    projectId: 'evide-school-parent',
    storageBucket: 'evide-school-parent.firebasestorage.app',
    iosBundleId: 'in.evide.school.parent',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0JFT7GrACfEUfSBmiWGfnJy9eF7grni4',
    appId: '1:727123421542:ios:f9d800b2c9340a7c3f80a7',
    messagingSenderId: '727123421542',
    projectId: 'evide-school-parent',
    storageBucket: 'evide-school-parent.firebasestorage.app',
    iosBundleId: 'com.example.evideSchoolParent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1QdS4T69GbIfuvgnJ9gEYpTjAB4vKg6g',
    appId: '1:727123421542:web:752a648b76ef18953f80a7',
    messagingSenderId: '727123421542',
    projectId: 'evide-school-parent',
    authDomain: 'evide-school-parent.firebaseapp.com',
    storageBucket: 'evide-school-parent.firebasestorage.app',
    measurementId: 'G-Q4N5KF74P1',
  );
}
